name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files changed
        run: |
          echo 'Files modified: ${{steps.files.outputs.files_updated}}'
          echo 'Files added: ${{steps.files.outputs.files_created}}'
          echo 'Files removed: ${{steps.files.outputs.files_deleted}}'
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files-changed: ${{steps.files.outputs.files_updated}} ${{steps.files.outputs.files_created}}
